### PR TITLE
Styling about us page and adding reset CSS file

### PR DESCRIPTION
**Pull request by AhmadAlkaati**
* Styling about us page.
*  adding reset CSS file that contains some basic styles .
* Adding new font to the website.
* Removing old google's font link and adding link of new one in CSS file instead.

### CODE REVIEW

**Review by josipgrgic — APPROVED** [review]
It is ok, but why are we doing this? The project is closed already so I don't see a reason to push anything more to the repo. If you want to continue to develop the web page, it might be wiser to create your own fork of the repo and continue development there

**Comment by AhmadAlkaati** [comment]
@josipgrgic I am sorry and I understand you but about us page which is a part of the project was not styled at all that's why I did some styles to it.
Thanks for approving pr. 
Is it okay to merge it?

**Comment by josipgrgic** [comment]
> @josipgrgic I am sorry and I understand you but about us page which is a part of the project was not styled at all that's why I did some styles to it.
> Thanks for approving pr.
> Is it okay to merge it?

It is ok, no worries. It is not a big deal. Just keep in mind that if you want to make bigger changes, please do them inside your own fork of the project and not this repo. We are done with the project so no further code should be pushed here.

**Comment by AhmadAlkaati** [comment]
> > @josipgrgic I am sorry and I understand you but about us page which is a part of the project was not styled at all that's why I did some styles to it.
> > Thanks for approving pr.
> > Is it okay to merge it?
> 
> It is ok, no worries. It is not a big deal. Just keep in mind that if you want to make bigger changes, please do them inside your own fork of the project and not this repo. We are done with the project so no further code should be pushed here.

Alright I get it :)
Thanks a lot

**Pull request merged**
